# Site settings
title: Jacob Wunder's Blog
email: public@jacobwunder.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I write about things that I think are interesting.
baseurl: ""
url: "http://jacobwunder.com"

footer_links:
  dribbble:
  email:
  facebook:
  flickr:
  github: jaywunder
  instagram:
  linkedin:
  pinterest:
  rss: Jacob Wunder's RSS # just type anything here for a working RSS icon
  twitter: jaywunder54
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Build settings
permalink: /:title/
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
