# Site settings
title: Jacob Wunder's Blog
email: public@jacobwunder.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I write about things that I think are interesting.
baseurl: ""
url: "http://jacobwunder.com"
github_username: jaywunder

# Build settings
markdown: kramdown
