# Site settings
title: Jacob Wunder's Blog
email: not.my.email@jacobwunder.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I write about things that I think are interesting.
baseurl: "/blag"
url: "http://jaywunder.github.io"
github_username:  jaywunder

# Build settings
markdown: kramdown
